package io.github.kidx

import kotlin.js.JsAny

/**
 * A store definition: its IndexedDB object-store name, its fields and its indexes. A store holds no
 * connection — operations exist only inside a [ReadScope] or [WriteScope] (decision 5), and this
 * class's own encode/decode are internal.
 *
 * ```kotlin
 * object Users : Store<User>("users", ::User) {
 *     val id by Field.UUID().primaryKey()
 *     val email by Field.Text()
 *     val byEmail by index(email, unique = true)
 * }
 * ```
 *
 * [factory] builds an empty row; kidx fills its slots. That is the whole row-construction cost per
 * read: one object plus one array.
 */
public abstract class Store<R : Row>(
    public val storeName: String,
    internal val factory: () -> R,
) {
    private val fields = mutableListOf<Field<*, *, R>>()
    private val indexes = mutableListOf<Index<R>>()
    private var generatedKey: Field.KeyField<*, *, R>? = null

    /** The declared fields, in declaration order, so `declaredFields[i].ordinal == i`. */
    public val declaredFields: List<Field<*, *, R>> get() = fields

    /** The declared indexes, in declaration order. */
    public val declaredIndexes: List<Index<R>> get() = indexes

    /**
     * The primary key: the fields marked with `primaryKey()`, in declaration order. Several of them
     * mean a composite key (IndexedDB's array `keyPath`).
     *
     * There is no fallback to "the field named id", unlike kormium: in IndexedDB the key path is fixed
     * when the store is created, and inferring it from a property name is exactly the hidden behaviour
     * this design refuses (decision 12).
     */
    public val primaryKey: List<Field.KeyField<*, *, R>>
        get() = primaryKeyCache ?: fields.filterIsInstance<Field.KeyField<*, *, R>>()
            .filter { it.isPrimaryKey }
            .ifEmpty {
                throw SchemaException(
                    "Store '$storeName' declares no primary key. Mark one field (or several, for a " +
                        "composite key) with primaryKey().",
                )
            }
            .also { primaryKeyCache = it }

    private var primaryKeyCache: List<Field.KeyField<*, *, R>>? = null

    /** Whether the primary key is generated by the engine (decision 12). */
    public val autoIncrement: Boolean get() = generatedKey != null

    internal fun addField(field: Field<*, *, R>) {
        field.ordinal = fields.size
        fields += field
        primaryKeyCache = null
    }

    internal fun addIndex(index: Index<R>) {
        indexes += index
    }

    internal fun markAutoIncrement(field: Field.KeyField<*, *, R>) {
        val existing = generatedKey
        if (existing != null) {
            throw SchemaException(
                "Store '$storeName' marks both '${existing.name}' and '${field.name}' as generated; " +
                    "IndexedDB generates at most one key per store.",
            )
        }
        generatedKey = field
    }

    // ---- the record boundary (decision 9) ----

    /**
     * Builds the record to store. Every declared field is written: a nullable field with no value
     * becomes an explicit null, so that on the way back "absent" means exactly one thing — the record
     * predates the field.
     *
     * An absent non-null field is refused here, before the engine sees it. IndexedDB has no column
     * defaults, so omitting the property would store a record that later fails to decode; the only
     * field allowed to be absent is a generated primary key.
     */
    internal fun encode(row: R): JsAny {
        val record = newRecord()
        for (field in fields) {
            val value = row.slotGet(field)
            if (value === ABSENT) {
                if (field.nullable) {
                    recordSet(record, field.name, null)
                    continue
                }
                if (field === generatedKey) continue // the engine fills it in
                throw RowMappingException(
                    "Cannot store a row of '$storeName': field '${field.name}' is non-null but has no " +
                        "value (expected ${field.type.description}).",
                )
            }
            recordSet(record, field.name, if (value == null) null else field.encodeUnchecked(value))
        }
        return record
    }

    /**
     * Builds a row from a stored record. A missing property becomes [ABSENT], which a non-null field
     * reports as a schema-evolution mismatch and a nullable field reads back as null. Properties the
     * schema does not declare are ignored — and therefore lost if the row is written back.
     */
    internal fun decode(record: JsAny): R {
        val slots = arrayOfNulls<Any?>(fields.size)
        for (field in fields) {
            val name = field.name
            if (!recordHas(record, name)) {
                slots[field.ordinal] = ABSENT
                if (!field.nullable) {
                    throw RowMappingException(
                        "Field '$name' of store '$storeName' is non-null (expected " +
                            "${field.type.description}) but the stored record has no such property. " +
                            "The record was most likely written before the field was added to the " +
                            "schema — add a migration that backfills it, or declare the field nullable.",
                    )
                }
                continue
            }
            val stored = recordGet(record, name)
            if (stored == null) {
                if (!field.nullable) {
                    throw RowMappingException(
                        "Field '$name' of store '$storeName' is non-null (expected " +
                            "${field.type.description}) but the stored value is null. The record does " +
                            "not match the schema.",
                    )
                }
                slots[field.ordinal] = null
                continue
            }
            slots[field.ordinal] = try {
                field.type.decode(stored)
            } catch (e: FieldTypeException) {
                throw RowMappingException(
                    "Field '$name' of store '$storeName': ${e.message}.",
                    cause = e,
                )
            }
        }
        return factory().also { it.adopt(slots, this) }
    }

    /** The key path IndexedDB is given when the store is created. */
    internal fun keyPath(): List<String> = primaryKey.map { it.name }
}

@Suppress("UNCHECKED_CAST")
private fun Field<*, *, *>.encodeUnchecked(value: Any): JsAny =
    (type as FieldType<Any>).encode(value)
